export const FETCH_USER = 'FETCH_USER';
export const FETCH_SURVEYS_START = 'FETCH_SURVEYS_START';
export const FETCH_SURVEYS_SUCCESS = 'FETCH_SURVEYS_SUCCESS';
export const FETCH_SURVEYS_FAIL = 'FETCH_SURVEYS_FAIL';
export const SET_PAGE = 'SET_PAGE';

export const STRIPE_PAYMENT = 'STRIPE_PAYMENT';
